import { Patient, MRDFile } from './types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    uhid: '1029384',
    name: 'Robert Miller',
    firstName: 'Robert',
    lastName: 'Miller',
    gender: 'Male',
    age: 72,
    phone: '+1 (555) 321-9876',
    dob: '1954-04-12',
    address: '42 Main St, Sector 12, Boston, MA',
    ward: 'Ward 4B',
    bed: 'B-102',
    department: 'Cardiology',
    attendingDoctor: 'Dr. Sarah Chen',
    crossConsultant: 'Dr. Anthony Fauci',
    status: 'Provisional Admission',
    labels: ['High Priority', 'Insurance'],
    admissionDate: '2026-06-12',
    plan: 'Insurance Covered',
    referredBy: 'Central Clinic',
    uploadedDocsCount: 2,
    initials: 'RM',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKhyL2PPUmXUmhQE9iBZ1B6jCrMNVVjyKne4oQoSdcjzYpTpnX9PvF87vV0_n4SlHeCm0OCKjT5wu0NsacSsNm7s-_1W3QgpCOWWZfVu3dtGA2AGjR6YdwK0eIQ4Yahc_xd1GEdC7JMPvLhqDuhP5Kp0dEWbLKDcbrH5gSgJrEL8SxC825PUmzJEIRgfFwgPpEsDaFq_9yajvdoFO7c9qrvLbMxGyrjf7UqwIi6_MZUfD47Wtad2dyowA4n-vIrJ5qNpTn6txyQAE'
  },
  {
    id: 'pat-2',
    uhid: '1029412',
    name: 'Sarah Jenkins',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    gender: 'Female',
    age: 68,
    phone: '+1 (555) 765-4321',
    dob: '1958-08-22',
    address: '15 Oak Ridge Rd, Lincoln, NE',
    ward: 'Ward 2A',
    bed: 'A-201',
    department: 'Neurology',
    attendingDoctor: 'Dr. Ashok Kumar',
    crossConsultant: 'Dr. Sarah Chen',
    status: 'Completed',
    labels: ['Insurance'],
    admissionDate: '2026-06-10',
    plan: 'Premium',
    referredBy: 'Dr. Ashok Kumar',
    uploadedDocsCount: 3,
    initials: 'SJ',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjqJhbKU6wsCnUdPoHtyOqX1czmHaxhfXINje-9E1FgLx6yvka05S3v7wPRDWn3V9735dpKSGJYFvJGAZ19pP8PzC0KhX7sMy-jJafFXvVa8pyyTqB38VktZD0DTIZBT9bGwYSy0n70AEI8PO4wCZg_ARicW_Ha_iB-1oZRe-NIWezWm77B-F8fZxxtXi8CA-bQAQEfGH72zrAVD-NZlpIBveRXLfIe_6atyuJ0JGx_zTWoux6vX-G9mRRYHKVGnzGEgQOoo8gDT0'
  },
  {
    id: 'pat-3',
    uhid: '1029455',
    name: 'Arthur Lewis',
    firstName: 'Arthur',
    lastName: 'Lewis',
    gender: 'Male',
    age: 75,
    phone: '+1 (555) 234-5678',
    dob: '1951-11-05',
    address: '89 Maple Dr, Springfield, IL',
    ward: 'ICU-1',
    bed: 'I-01',
    department: 'Intensive Care',
    attendingDoctor: 'Dr. Marcus Wright',
    crossConsultant: 'Dr. Sarah Chen',
    status: 'MRD Pending',
    labels: ['Payment Defaulter'],
    admissionDate: '2026-06-13',
    plan: 'Basic',
    referredBy: 'Emergency Inbound',
    uploadedDocsCount: 1,
    initials: 'AL',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDoWA_MquWUSiOkqD3NECzhu4_My-XONmZ1T8tUTLBiYIVJeLKAdR7bU_wjQMbYAifQu2tW_OwtTwenbnvX23SHCqgOR150hwvbXejPhVzVyL-Iwbs7eo2jXrgUF-qwYWjEAH8-AAvliIaHAuPe4_yCGb9Lv7KopCtcAljUrz72WTCdNEijBNXfnXC6SKg4t_bLOvq5sSgKt-vAoD-bg09zZzu4v9RFSjOfOgOuAvhdmik4jQ9F4-QsMrShVq1cCKkcv6TatIhqo-c'
  },
  {
    id: 'pat-4',
    uhid: '1029501',
    name: 'Evelyn Thorne',
    firstName: 'Evelyn',
    lastName: 'Thorne',
    gender: 'Female',
    age: 82,
    phone: '+1 (555) 890-1234',
    dob: '1944-01-18',
    address: '202 Pine St, Augusta, GA',
    ward: 'Ward 4B',
    bed: 'B-105',
    department: 'Cardiology',
    attendingDoctor: 'Dr. Sarah Chen',
    crossConsultant: 'Dr. Ashok Kumar',
    status: 'Discharged',
    labels: ['Insurance'],
    admissionDate: '2026-06-08',
    plan: 'Insurance Covered',
    referredBy: 'Nursing Home Referral',
    uploadedDocsCount: 4,
    initials: 'ET',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJYkEZRF9eFx6tc0LBKMIfxtp6CggZ0TETUUnjsgN2K-cWeZRSBZXkEkTXF44Bz3ZnWhMP86McZeholVgBuXVTveZGApveG9BlR_2Bnbztrd-4XrNdbThRkPlYxFng8rimjqerDLESgwRw1ROWJjFp3zE0Tby90RSAgGNeIamoNEoT65qoKAMRjQujzjrPyYXXH4FYJqR7rlbLaeYvENfBwGJQkkV-Ygki7pPfUEHi3ai9vEpD83KyvzsWNxB_R-3pZUs-ZCmhr0c'
  }
];

export const INITIAL_FILES: MRDFile[] = [
  {
    id: 'doc-1',
    fileName: 'Lab_Report_Feb24.pdf',
    patientName: 'Sarah Jenkins',
    uhid: '1029412',
    category: 'Clinical',
    uploadDate: '24 Feb 2024, 09:12 AM',
    status: 'Verified',
    securityLevel: 'High',
    fileSize: '2.4 MB',
    authoredBy: 'Dr. Sarah Chen',
    notes: 'Patient shows significant improvement in creatinine levels since previous testing. Continue current medication regimen.',
    previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAphuincDntJzYNjDHY_ALBJPdi4Qn5Msgg9n3wCp8nnLwtFUTmoI9R6uGzOwm0Kt_cg_leavX7BKPTVczmKG913zVSIhyyTVltO_0aLluPseeoWUlU00D8dk84Gd_aj9pok6QZui9dxPijqSUxkElLeLZso2lKydO2mIjU7J_GiIjdaguzY8IEwtzxHVfqsmSWkfxVwjtAlkokwJEBaaGMWdR-8Tz1742zU7czSm2b01p6iBlXgTvOv5qc79tOimSCxxMhAdiNFe0'
  },
  {
    id: 'doc-2',
    fileName: 'MRI_Scan_Lumbar.jpg',
    patientName: 'Marcus Chen',
    uhid: '99301221',
    category: 'Imaging',
    uploadDate: '23 Feb 2024, 04:45 PM',
    status: 'Pending Review',
    securityLevel: 'Restricted',
    fileSize: '8.1 MB',
    authoredBy: 'Dr. Marcus Wright',
    notes: 'L4-L5 disc protrusion noted with secondary stenosis. Suggest referral for physical therapy evaluation and follow-up appointment in 14 days.',
    previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDfbPkYfyLrVxamJLNjhNsy4oruMNRz5DutSVqjvoqhqzK-kwL5V4MTNfSUHnshf_HZOmBUECLlFVSSSbK2TovQ81OGNI7kbiUGogW_6D4vMmgy7dKgenkx2Oyv6tgpwUB04q8JK3lOYlsn6enXEJZFZe0a-EUomYSQgAoNWYwlSorLwlZ0Bjuepc0zaApMEAcNcUI-vW-fafQxHVznWopmA9_LMR2eSPCCVDYsxcmJbspkWaEkoZO1AOB1BlHO0AArvWCVJER_SAY'
  },
  {
    id: 'doc-3',
    fileName: 'Consent_Form_Surgery.doc',
    patientName: 'Elena Rodriguez',
    uhid: '77102293',
    category: 'Administrative',
    uploadDate: '23 Feb 2024, 02:20 PM',
    status: 'Flagged',
    securityLevel: 'Standard',
    fileSize: '1.1 MB',
    authoredBy: 'Dr. Sarah Chen',
    notes: 'Signed treatment consent copy for laparoscopic cholecystectomy. Signature verified by attending nurse, but witness line requires notary countersign.',
    previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDoWA_MquWUSiOkqD3NECzhu4_My-XONmZ1T8tUTLBiYIVJeLKAdR7bU_wjQMbYAifQu2tW_OwtTwenbnvX23SHCqgOR150hwvbXejPhVzVyL-Iwbs7eo2jXrgUF-qwYWjEAH8-AAvliIaHAuPe4_yCGb9Lv7KopCtcAljUrz72WTCdNEijBNXfnXC6SKg4t_bLOvq5sSgKt-vAoD-bg09zZzu4v9RFSjOfOgOuAvhdmik4jQ9F4-QsMrShVq1cCKkcv6TatIhqo-c'
  },
  {
    id: 'doc-4',
    fileName: 'Discharge_Summary_101.pdf',
    patientName: 'Robert Miller',
    uhid: '1029384',
    category: 'Clinical',
    uploadDate: '22 Feb 2024, 11:30 AM',
    status: 'Verified',
    securityLevel: 'High',
    fileSize: '1.8 MB',
    authoredBy: 'Dr. Sarah Chen',
    notes: 'Standard discharge dispatch summarizing medication change from heavy IV beta-blockers to oral ACE-inhibitors. Clinical outcome fully synchronized.',
    previewUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3CFOFmvkz0vLGgzTCfau8BA-n4fPOxmtJK5f80AOmIU7ysms4X_QndKdCYHJoD1kWStMlEFyNe8ra487ef3_NcPQLPy4J_wPNkjUICKPiby0xNgErHmf7TOQycGixRThtHF2wX5A4eOSwsw2_qUQee1-ZrjVcVBu7Zkk-SQmO1eRUGfbPNgdpdqjMLLCwB2LBFka3eWjBDg6sQRwCGbEwwXHm547Z6RmOPE01jnFuWVs40QW-7UHrvMR-mXVTYbtuxhf-gMijVHo'
  }
];
